apiVersion: v1
kind: ServiceAccount
metadata:
  name: franta
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pepa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
  - kind: Group
    name: kubernetes_ns_counter
  - kind: ServiceAccount
    name: franta
  - kind: ServiceAccount
    name: pepa
