apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: main
          image: redis:8
          ports:
            - containerPort: 6379
          startupProbe:
            tcpSocket:
              port: 6379
            periodSeconds: 2
            failureThreshold: 20
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            periodSeconds: 1
          resources:
            requests:
              cpu: 50m
              memory: 20Mi
            limits:
              cpu: 100m
              memory: 40Mi
